import { readFileSync } from 'node:fs';
import booleanPointInPolygon from '@turf/boolean-point-in-polygon';
import type {
  Feature,
  FeatureCollection,
  MultiPolygon,
  Polygon,
} from 'geojson';

export type Coordinates = { latitude: number; longitude: number };
export type Area = Feature<Polygon | MultiPolygon>;

/** Frozen isochrone generated by `npm run geo:isochrone`, shipped next to this file. */
export const ISOCHRONE_FILENAME = 'isochrone.geojson';

/** Straight-line stand-in for the driving time until the isochrone is generated. */
export const FALLBACK_RADIUS_KM = 45;

/** Returns null when the file has not been generated yet. */
export function loadIsochrone(): Area | null {
  try {
    const url = new URL(`./${ISOCHRONE_FILENAME}`, import.meta.url);
    const parsed = JSON.parse(readFileSync(url, 'utf8')) as
      FeatureCollection | Area;
    return parsed.type === 'FeatureCollection'
      ? ((parsed.features[0] as Area) ?? null)
      : parsed;
  } catch {
    return null;
  }
}

/** Great-circle distance in kilometres. */
export function distanceKm(from: Coordinates, to: Coordinates): number {
  const earthRadiusKm = 6371;
  const toRad = (deg: number) => (deg * Math.PI) / 180;
  const dLat = toRad(to.latitude - from.latitude);
  const dLon = toRad(to.longitude - from.longitude);
  const a =
    Math.sin(dLat / 2) ** 2 +
    Math.cos(toRad(from.latitude)) *
      Math.cos(toRad(to.latitude)) *
      Math.sin(dLon / 2) ** 2;
  return 2 * earthRadiusKm * Math.asin(Math.sqrt(a));
}

/** Point-in-polygon when the isochrone exists, radius around the centre otherwise. */
export function isWithinArea(
  area: Area | null,
  center: Coordinates,
  point: Coordinates,
): boolean {
  if (area)
    return booleanPointInPolygon([point.longitude, point.latitude], area);
  return distanceKm(center, point) <= FALLBACK_RADIUS_KM;
}
